# This workflow will build, deploy a .NET project from the src folder and run Swagger
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and Swagger Deployment

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      run: dotnet test src --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src -c Release -o out
    - name: Run Application
      run: |
        dotnet out/gRPCService.dll > application.log 2>&1 &
      env:
        ASPNETCORE_URLS: http://+:5000
    - name: Wait for Application
      run: |
        sleep 30
    - name: Check Application Logs
      run: cat application.log
    - name: Verify Swagger
      run: |
        curl -f http://localhost:5000/swagger/index.html
